name: Pull Request Target

on:
  pull_request_target

jobs:
  pull-request-target:
    runs-on: ubuntu-latest
    steps:
      - name: Run command
        run: |
          echo "This is pull request target from origin"
          ls -la
