name: Pull Request

on:
  pull_request

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to repo
        uses: actions/checkout@v4

      - name: Run command
        run: |
          echo "This is pull request from origin"
          echo ${{ github.event.pull_request.head.repo.full_name }}
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ vars.TEST_VARIABLE }}
          ls -la
